# CMake generated Testfile for 
# Source directory: /Volumes/SN/Developer/coco
# Build directory: /Volumes/SN/Developer/coco/build_ts
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_coro "/Volumes/SN/Developer/coco/build_ts/test_coro")
set_tests_properties(test_coro PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_channel "/Volumes/SN/Developer/coco/build_ts/test_channel")
set_tests_properties(test_channel PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_timer "/Volumes/SN/Developer/coco/build_ts/test_timer")
set_tests_properties(test_timer PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_io "/Volumes/SN/Developer/coco/build_ts/test_io")
set_tests_properties(test_io PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_stack "/Volumes/SN/Developer/coco/build_ts/test_stack")
set_tests_properties(test_stack PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_stack_overflow "/Volumes/SN/Developer/coco/build_ts/test_stack_overflow")
set_tests_properties(test_stack_overflow PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_cancel "/Volumes/SN/Developer/coco/build_ts/test_cancel")
set_tests_properties(test_cancel PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_fd_table "/Volumes/SN/Developer/coco/build_ts/test_fd_table")
set_tests_properties(test_fd_table PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_iouring "/Volumes/SN/Developer/coco/build_ts/test_iouring")
set_tests_properties(test_iouring PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_io_backend "/Volumes/SN/Developer/coco/build_ts/test_io_backend")
set_tests_properties(test_io_backend PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_batch_io "/Volumes/SN/Developer/coco/build_ts/test_batch_io")
set_tests_properties(test_batch_io PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_io_options "/Volumes/SN/Developer/coco/build_ts/test_io_options")
set_tests_properties(test_io_options PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_syscall_count "/Volumes/SN/Developer/coco/build_ts/test_syscall_count")
set_tests_properties(test_syscall_count PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_poll_macos "/Volumes/SN/Developer/coco/build_ts/test_poll_macos")
set_tests_properties(test_poll_macos PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_event_loop "/Volumes/SN/Developer/coco/build_ts/test_event_loop")
set_tests_properties(test_event_loop PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_aging "/Volumes/SN/Developer/coco/build_ts/test_aging")
set_tests_properties(test_aging PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_lifecycle "/Volumes/SN/Developer/coco/build_ts/test_lifecycle")
set_tests_properties(test_lifecycle PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_priority "/Volumes/SN/Developer/coco/build_ts/test_priority")
set_tests_properties(test_priority PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_signal "/Volumes/SN/Developer/coco/build_ts/test_signal")
set_tests_properties(test_signal PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_exit "/Volumes/SN/Developer/coco/build_ts/test_exit")
set_tests_properties(test_exit PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_sleep "/Volumes/SN/Developer/coco/build_ts/test_sleep")
set_tests_properties(test_sleep PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_aging_trigger "/Volumes/SN/Developer/coco/build_ts/test_aging_trigger")
set_tests_properties(test_aging_trigger PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_stack_pool_multi "/Volumes/SN/Developer/coco/build_ts/test_stack_pool_multi")
set_tests_properties(test_stack_pool_multi PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_stack_pool_mt "/Volumes/SN/Developer/coco/build_ts/test_stack_pool_mt")
set_tests_properties(test_stack_pool_mt PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_locked_queue "/Volumes/SN/Developer/coco/build_ts/test_locked_queue")
set_tests_properties(test_locked_queue PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_safepoint "/Volumes/SN/Developer/coco/build_ts/test_safepoint")
set_tests_properties(test_safepoint PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_global_sched "/Volumes/SN/Developer/coco/build_ts/test_global_sched")
set_tests_properties(test_global_sched PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_runq "/Volumes/SN/Developer/coco/build_ts/test_runq")
set_tests_properties(test_runq PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_sched "/Volumes/SN/Developer/coco/build_ts/test_sched")
set_tests_properties(test_sched PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_channel_mt "/Volumes/SN/Developer/coco/build_ts/test_channel_mt")
set_tests_properties(test_channel_mt PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_netpoller_mt "/Volumes/SN/Developer/coco/build_ts/test_netpoller_mt")
set_tests_properties(test_netpoller_mt PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_context_api "/Volumes/SN/Developer/coco/build_ts/test_context_api")
set_tests_properties(test_context_api PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_context_coro "/Volumes/SN/Developer/coco/build_ts/test_context_coro")
set_tests_properties(test_context_coro PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_platform_abstraction "/Volumes/SN/Developer/coco/build_ts/test_platform_abstraction")
set_tests_properties(test_platform_abstraction PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_sched_stats "/Volumes/SN/Developer/coco/build_ts/test_sched_stats")
set_tests_properties(test_sched_stats PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_coco_go "/Volumes/SN/Developer/coco/build_ts/test_coco_go")
set_tests_properties(test_coco_go PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_sched_hooks "/Volumes/SN/Developer/coco/build_ts/test_sched_hooks")
set_tests_properties(test_sched_hooks PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
add_test(test_context_value "/Volumes/SN/Developer/coco/build_ts/test_context_value")
set_tests_properties(test_context_value PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/SN/Developer/coco/CMakeLists.txt;176;add_test;/Volumes/SN/Developer/coco/CMakeLists.txt;0;")
